name: Quality pipeline
on:
  push:
    branches: ["*"]
  schedule:
    - cron: "0 */12 * * *"

jobs:
  quality_pipeline:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)
