name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DT_CI_AT }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      # Prepare
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      # Publish to NPM
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish

      # Deploy to CDN (trigger)
      - name: Obtain release version
        run: echo "RELEASE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      - name: Tirgger deploy to CDN
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy to CDN
          token: ${{ secrets.DT_CI_AT }}
          inputs: '{ "version": "${{ env.RELEASE_VERSION }}" }'

      # Bump version to next snapshot
      - name: Bump snapshot version
        run: |
          npm run bump -- --version=patch --snapshot
          npm install
          echo "SNAPSHOT_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Push changes
        run: |
          git fetch
          git config user.email "gullerya@gmail.com"
          git config user.name "data-tier CI"
          git add --all
          git commit -m "set version to ${{ env.SNAPSHOT_VERSION }}"
          git push origin HEAD:main