name: Publish (NPM)

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DT_CI_AT }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish

      # Trigger deploy to CDN
      - name: Obtain release version
        run: echo "RELEASE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      - name: Tirgger deploy to CDN
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Deploy (CDN)"
          token: ${{ secrets.DT_CI_AT }}
          inputs: '{ "version": "${{ env.RELEASE_VERSION }}" }'
