name: Deploy (CDN)

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (eg 1.2.3)"
        required: true

jobs:
  release-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      # Get release version
      - name: Get release version
        run: echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      # Pull the version to be deployed
      - name: Install
        run: npm install -E data-tier@${{ env.RELEASE_VERSION }}

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET }}
        run: aws s3 sync ./node_modules/data-tier/dist s3://${{ secrets.AWS_LIBS_BUCKET }}/data-tier/${{ env.RELEASE_VERSION }} --delete --cache-control public,max-age=172800,immutable
